// ── Curated tourist destinations for the "Plan Your Trip" page ───────────────
// 25 famous Indian places. Each carousel is built from these fields:
//   • `nearby`     — places to visit around the destination
//   • `thingsToDo` — experiences to have there
// Carousel images are fetched from loremflickr (keyless, themed by keyword);
// see `slideImage()` for how the URL is derived. `dest` is what we pass to the
// booking form as the pre-filled drop location (`/?advised=1&dest=...`).

const DESTINATIONS = [
  {
    id: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    dest: "Agra, Uttar Pradesh",
    tagline: "Where the Taj Mahal rises at dawn",
    nearby: ["Fatehpur Sikri", "Mathura", "Vrindavan", "Bharatpur"],
    thingsToDo: [
      "Watch sunrise at the Taj Mahal",
      "Explore the red-sandstone Agra Fort",
      "Shop for marble inlay handicrafts",
    ],
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    dest: "Jaipur, Rajasthan",
    tagline: "The majestic Pink City",
    nearby: ["Amber Fort", "Ajmer", "Pushkar"],
    thingsToDo: [
      "Photograph the Hawa Mahal facade",
      "Climb Nahargarh Fort for city views",
      "Bargain in the Johari Bazaar",
    ],
  },
  {
    id: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    dest: "Udaipur, Rajasthan",
    tagline: "The romantic City of Lakes",
    nearby: ["Kumbhalgarh", "Mount Abu", "Chittorgarh"],
    thingsToDo: [
      "Boat ride across Lake Pichola",
      "Tour the grand City Palace",
      "Catch sunset at Sajjangarh",
    ],
  },
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state: "Rajasthan",
    dest: "Jaisalmer, Rajasthan",
    tagline: "The Golden City of the Thar",
    nearby: ["Sam Sand Dunes", "Kuldhara", "Longewala"],
    thingsToDo: [
      "Camel safari across the dunes",
      "Sleep under stars in a desert camp",
      "Wander the living Sonar Qila",
    ],
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    dest: "Jodhpur, Rajasthan",
    tagline: "The Blue City under the fort",
    nearby: ["Mandore", "Osian", "Bishnoi Villages"],
    thingsToDo: [
      "Explore the towering Mehrangarh Fort",
      "Lose yourself in the blue lanes",
      "Visit the marble Jaswant Thada",
    ],
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    dest: "Varanasi, Uttar Pradesh",
    tagline: "The spiritual heart of India",
    nearby: ["Sarnath", "Bodh Gaya", "Prayagraj"],
    thingsToDo: [
      "Witness the Ganga aarti at dusk",
      "Sunrise boat ride along the ghats",
      "Walk the timeless old-city lanes",
    ],
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    dest: "Rishikesh, Uttarakhand",
    tagline: "Yoga capital on the Ganga",
    nearby: ["Haridwar", "Devprayag", "Neelkanth"],
    thingsToDo: [
      "White-water raft the Ganga",
      "Cross the swaying Laxman Jhula",
      "Evening aarti at Triveni Ghat",
    ],
  },
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    dest: "Manali, Himachal Pradesh",
    tagline: "Gateway to the high Himalayas",
    nearby: ["Solang Valley", "Rohtang Pass", "Kasol"],
    thingsToDo: [
      "Paraglide over Solang Valley",
      "Play in the snow at Rohtang",
      "Cafe-hop through Old Manali",
    ],
  },
  {
    id: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    dest: "Shimla, Himachal Pradesh",
    tagline: "The colonial Queen of the Hills",
    nearby: ["Kufri", "Chail", "Naldehra"],
    thingsToDo: [
      "Stroll along the historic Mall Road",
      "Ride the UNESCO toy train",
      "Hike up to Jakhoo Temple",
    ],
  },
  {
    id: "leh",
    name: "Leh",
    state: "Ladakh",
    dest: "Leh, Ladakh",
    tagline: "Land of high passes & blue lakes",
    nearby: ["Pangong Lake", "Nubra Valley", "Khardung La"],
    thingsToDo: [
      "Drive to the surreal Pangong Lake",
      "Visit cliff-top monasteries",
      "Camel ride on Nubra's dunes",
    ],
  },
  {
    id: "srinagar",
    name: "Srinagar",
    state: "Jammu & Kashmir",
    dest: "Srinagar, Jammu and Kashmir",
    tagline: "Paradise on earth",
    nearby: ["Gulmarg", "Pahalgam", "Sonamarg"],
    thingsToDo: [
      "Shikara ride on Dal Lake",
      "Stay aboard a heritage houseboat",
      "Wander the Mughal gardens",
    ],
  },
  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    dest: "Goa",
    tagline: "Sun, sand and serenity",
    nearby: ["Old Goa", "Dudhsagar Falls", "Anjuna"],
    thingsToDo: [
      "Unwind on Baga & Palolem beaches",
      "Try parasailing & jet-skiing",
      "Tour the Portuguese-era churches",
    ],
  },
  {
    id: "munnar",
    name: "Munnar",
    state: "Kerala",
    dest: "Munnar, Kerala",
    tagline: "Rolling tea-garden hills",
    nearby: ["Thekkady", "Eravikulam", "Top Station"],
    thingsToDo: [
      "Walk through emerald tea plantations",
      "Spot the Nilgiri tahr",
      "Tour a fragrant spice garden",
    ],
  },
  {
    id: "alleppey",
    name: "Alleppey",
    state: "Kerala",
    dest: "Alleppey, Kerala",
    tagline: "The Venice of the East",
    nearby: ["Kumarakom", "Kuttanad", "Marari Beach"],
    thingsToDo: [
      "Cruise the backwaters on a houseboat",
      "Stroll a waterside village",
      "Feast on a banana-leaf sadhya",
    ],
  },
  {
    id: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    dest: "Ooty, Tamil Nadu",
    tagline: "Queen of the Nilgiris",
    nearby: ["Coonoor", "Doddabetta", "Pykara"],
    thingsToDo: [
      "Ride the Nilgiri toy train",
      "Row a boat on Ooty Lake",
      "Roam the Botanical Gardens",
    ],
  },
  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    dest: "Hampi, Karnataka",
    tagline: "Ruins of a forgotten empire",
    nearby: ["Anegundi", "Tungabhadra Dam", "Badami"],
    thingsToDo: [
      "Explore the Vijayanagara ruins",
      "Catch sunset from Matanga Hill",
      "Float the river in a coracle",
    ],
  },
  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    dest: "Coorg, Karnataka",
    tagline: "The Scotland of India",
    nearby: ["Madikeri", "Dubare", "Abbey Falls"],
    thingsToDo: [
      "Tour a working coffee estate",
      "Meet elephants at Dubare camp",
      "Trek up to Tadiandamol peak",
    ],
  },
  {
    id: "mysore",
    name: "Mysore",
    state: "Karnataka",
    dest: "Mysore, Karnataka",
    tagline: "The royal City of Palaces",
    nearby: ["Srirangapatna", "Chamundi Hills", "Brindavan Gardens"],
    thingsToDo: [
      "Tour the illuminated Mysore Palace",
      "Climb to Chamundeshwari Temple",
      "Watch the Brindavan light show",
    ],
  },
  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    state: "Maharashtra",
    dest: "Mahabaleshwar, Maharashtra",
    tagline: "The strawberry hill station",
    nearby: ["Panchgani", "Pratapgad", "Wai"],
    thingsToDo: [
      "Pick fresh strawberries from a farm",
      "Boat across Venna Lake",
      "Sunset from Arthur's Seat",
    ],
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    dest: "Darjeeling, West Bengal",
    tagline: "Land of the thunderbolt",
    nearby: ["Kalimpong", "Mirik", "Ghum"],
    thingsToDo: [
      "Sunrise over Kanchenjunga at Tiger Hill",
      "Ride the Himalayan toy train",
      "Sip chai amid the tea gardens",
    ],
  },
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    dest: "Gangtok, Sikkim",
    tagline: "The cloud-kissed capital",
    nearby: ["Tsomgo Lake", "Nathula Pass", "Rumtek"],
    thingsToDo: [
      "Glide over town on the ropeway",
      "Visit the glacial Tsomgo Lake",
      "Evening walk down MG Marg",
    ],
  },
  {
    id: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    dest: "Amritsar, Punjab",
    tagline: "Home of the Golden Temple",
    nearby: ["Wagah Border", "Jallianwala Bagh", "Tarn Taran"],
    thingsToDo: [
      "Seek darshan at the Golden Temple",
      "Cheer the Wagah border ceremony",
      "Share a meal at the langar",
    ],
  },
  {
    id: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    dest: "Khajuraho, Madhya Pradesh",
    tagline: "Temples of timeless artistry",
    nearby: ["Panna National Park", "Raneh Falls", "Orchha"],
    thingsToDo: [
      "Admire the Western Group of Temples",
      "Watch the sound & light show",
      "Safari through Panna's forests",
    ],
  },
  {
    id: "pondicherry",
    name: "Pondicherry",
    state: "Puducherry",
    dest: "Pondicherry",
    tagline: "A slice of France in India",
    nearby: ["Auroville", "Mahabalipuram", "Chunnambar"],
    thingsToDo: [
      "Wander the colourful French Quarter",
      "Sunrise on Promenade Beach",
      "Find calm at Auroville's Matrimandir",
    ],
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    state: "Andaman & Nicobar",
    dest: "Andaman and Nicobar Islands",
    tagline: "Emerald isles of the Bay",
    nearby: ["Havelock Island", "Neil Island", "Ross Island"],
    thingsToDo: [
      "Scuba dive off Havelock",
      "Sunset at Radhanagar Beach",
      "Cellular Jail light & sound show",
    ],
  },
];

export default DESTINATIONS;
